import { ApplicationCategories } from './application_categories';
import { Applications } from './applications';
import { BannerInfo } from './banner_info';
import { DocumentCategories } from './document_categories';
import { Documents } from './documents';
import { GrafikInfo } from './grafik_info';
import { News } from './news';
import { NewsCategories } from './news_categories';
import { OrganizationDocuments } from './organization_documents';
import { OrganizationPejabat } from './organization_pejabat';
import { OrganizationTypes } from './organization_types';
import { Organizations } from './organizations';
import { PortalWebSettings } from './portal_web_settings';
import { PublicServices } from './public_services';
import { WebAduanPublik } from './web_aduan_publik';
import { WebNews } from './web_news';
import { Websites } from './websites';

export type DirectusItemsType = {
  application_categories: ApplicationCategories;
  applications: Applications;
  banner_info: BannerInfo;
  document_categories: DocumentCategories;
  documents: Documents;
  grafik_info: GrafikInfo;
  news: News;
  news_categories: NewsCategories;
  organization_documents: OrganizationDocuments;
  organization_pejabat: OrganizationPejabat;
  organization_types: OrganizationTypes;
  organizations: Organizations;
  portal_web_settings: PortalWebSettings;
  public_services: PublicServices;
  websites: Websites;
  web_aduan_publik: WebAduanPublik;
  web_news: WebNews;
};
export type ApiItemsType = DirectusItemsType;
