name: Main App Image
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build-app-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Create apps/main/.env.local file'
        run: |
          echo BACKEND_URL=${{ secrets.BACKEND_TOKEN }} >> apps/main/.env.local
          echo BACKEND_TOKEN=${{ secrets.BACKEND_TOKEN }} >> apps/main/.env.local
          echo NEW_RELIC_APP_NAME=${{ secrets.NEW_RELIC_APP_NAME }} >> apps/main/.env.local
          echo NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }} >> apps/main/.env.local
          echo NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID }} >> apps/main/.env.local
          echo NEXT_PUBLIC_MAIN_TITLE="Portal Resmi Pemkab Bolsel" >> apps/main/.env.local

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - uses: actions/cache@v3
        with:
          path: ./dist
          key: ${{ runner.os }}-DIST-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-DIST-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build App Image
        run: yarn nx run main:build-app-image --push
