name: portal-main-push

on:
  push:
    paths:
      - "portal-main/**"
      - ".github/workflows/ci.yml"


jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: codeup-id/portal-web-frontend
          path: ./main

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ./main/apps/bolsel
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: portal-main push image
        run: make push-image c=bolsel/portal-main
        working-directory: ./main

