name: portal-main-push

on:
  push:
    paths:
      - "portal-main/**"
      - "websites/**"
      - "_libs/**"
      - ".github/workflows/push-images.yml"


jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: upiksaleh/portal-web-frontend
          path: .

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ./apps/bolsel
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install project dependencies
        run: yarn
        working-directory: .

      - name: portal-main push image
        run: make push-image c=bolsel/portal-main
        working-directory: .

      - name: websites push image
        run: make push-image c=bolsel/websites
        working-directory: .
        env:
          NEXT_PUBLIC_API_RESOURCE_BASE_URL: https://bolselkab.go.id/api/resources/

